CREATE TABLE starlink_spacetrack
(
  starlink_id character varying NOT NULL,
  ccsds_omm_vers character varying,
  comment character varying,
  creation_date character varying,
  originator character varying,
  object_name character varying(20),
  object_id character varying,
  center_name character varying,
  ref_frame character varying,
  time_system character varying,
  mean_element_theory character varying,
  epoch character varying,
  mean_motion Float,
  eccentricity Float,
  inclination Float,
  ra_of_asc_node Float,
  arg_of_pericenter Float,
  mean_anomaly Float,
  ephemeris_type Float,
  classification_type character varying,
  norad_cat_id Int,
  element_set_no Int,
  rev_at_epoch Int,
  bstar Float,
  mean_motion_dot Float,
  mean_motion_ddot Float,
  semimajor_axis Float,
  period Float,
  apoapsis Float,
  periapsis Float,
  object_type character varying,
  rcs_size character varying,
  country_code character varying,
  launch_date character varying,
  site character varying,
  decay_date character varying,
  decayed Int,
  file Int,
  gp_id Int,
  tle_line0 character varying,
  tle_line1 character varying,
  tle_line2 character varying,
  row_updated timestamp with time zone NOT NULL,
  CONSTRAINT starlink_spacetrack_pkey PRIMARY KEY (starlink_id),
  CONSTRAINT fk_starlinks
    FOREIGN KEY(starlink_id)
      REFERENCES starlinks(starlink_id),
  UNIQUE(starlink_id)
)