CREATE TABLE ships
(
  id character varying NOT NULL,
  legacy_id character varying,
  name character varying,
  type character varying,
  active Boolean,
  model character varying,
  roles text[],
  imo Int,
  mmsi Int,
  abs Int,
  class Int,
  mass_kg Int,
  mass_lbs Int,
  year_built Int,
  home_port character varying,
  status character varying,
  speed_kn Int,
  course_deg Int,
  latitude Float,
  longitude Float,
  last_ais_update Int,
  link character varying,
  image character varying,
  launches text[],
  row_updated timestamp with time zone NOT NULL,
  CONSTRAINT ships_pkey PRIMARY KEY (id)
)