#[derive(Queryable)]
pub struct Roadster {
  pub apoapsis_au: Option<f64>,
  pub details: Option<String>,
  pub earth_distance_mi: Option<f64>,
  pub earth_distance_km: Option<f64>,
  pub eccentricity: Option<f64>,
  pub epoch_jd: Option<f64>,
  pub id: String,
  pub inclination: Option<f64>,
  pub launch_date_unix: Option<i32>,
  pub launch_date_utc: Option<String>,
  pub launch_mass_kg: Option<i32>,
  pub launch_mass_lbs: Option<i32>,
  pub longitude: Option<f64>,
  pub mars_distance_km: Option<f64>,
  pub mars_distance_mi: Option<f64>,
  pub name: Option<String>,
  pub norad_id: Option<i32>,
  pub orbit_type: Option<String>,
  pub periapsis_arg: Option<f64>,
  pub periapsis_au: Option<f64>,
  pub period_days: Option<f64>,
  pub semi_major_axis_au: Option<f64>,
  pub speed_kph: Option<f64>,
  pub speed_mph: Option<f64>,
  pub video: Option<String>,
  pub wikipedia: Option<String>,
  pub flickr_images: Option<Vec<String>>,
}