CREATE TABLE roadster_info
(
    apoapsis_au double precision,
    details text COLLATE pg_catalog."default",
    earth_distance_mi double precision,
    earth_distance_km double precision,
    eccentricity double precision,
    epoch_jd double precision,
    id character varying COLLATE pg_catalog."default" NOT NULL,
    inclination double precision,
    launch_date_unix integer,
    launch_date_utc varchar,
    launch_mass_kg integer,
    launch_mass_lbs integer,
    longitude double precision,
    mars_distance_km double precision,
    mars_distance_mi double precision,
    name character varying COLLATE pg_catalog."default",
    norad_id integer,
    orbit_type character varying COLLATE pg_catalog."default",
    periapsis_arg double precision,
    periapsis_au double precision,
    period_days double precision,
    semi_major_axis_au double precision,
    speed_kph double precision,
    speed_mph double precision,
    video character varying COLLATE pg_catalog."default",
    wikipedia character varying COLLATE pg_catalog."default",
    flickr_images text[] COLLATE pg_catalog."default",
    CONSTRAINT roadster_info_pkey PRIMARY KEY (id)
)